module.exports = {
    GRAPHQL_API: 'http://13.234.125.143/',
    // SERVERLESS_API: 'https://w0sujgfj39.execute-api.us-east-2.amazonaws.com',
    PORT: 8000,
    SET_TIMEOUT: 1000 * 60 * 5,
    WINDOW_MS: 1000 * 60 * 1,
    MAX_API_LIMITER: 500,
    Swap_DATA: "data/Amm_Transaction/Swap_data.json",
    AddLiquidity_DATA: "data/Amm_Transaction/AddLiquidity_data.json",
    RemoveLiquidity_DATA: "data/Amm_Transaction/RemoveLiquidity_data.json",
    Mint_DATA: "data/Main_Transaction/Mint_data.json",
    Burn_DATA: "data/Main_Transaction/Burn_data.json",
    Deposit_DATA: "data/Main_Transaction/Deposit_data.json",
    Withdraw_DATA: "data/Main_Transaction/Withdraw_data.json",
    Oven_DATA: "data/Ovens/Ovens_data.json",
    Drift_DATA: "data/Main_Data/Drift_Data.json",
    Target_DATA_One: "data/Main_Data/TargetOne_data.json",
}